/-
WSC/Goldens/TermsCheck.lean — GENERATED FILE, DO NOT EDIT BY HAND.

The gate that makes `WSC/Goldens/Terms.lean` trustworthy (task Y4 step 1).
Generated by `WSC/Goldens/gen-vectors.py` alongside `Vectors.lean` and
`Terms.lean`.

`Terms.lean` holds the goldens as `Data` LITERALS, produced by the CBOR decoder
inside the generator (needed because Blaster cannot normalise PCB's `partial`
hex/CBOR decoders — see the header of `Terms.lean`).  This module proves, for
every one of the 13 contexts, 13 redeemers and 19 script
parameters, that the literal is EXACTLY what PlutusCoreBlaster's own CBOR
decoder produces from the golden hex:

    dataOfHex <golden hex> = some <generated literal>

All 45 payload equalities are discharged by `native_decide` (kernel
`decide` is not an option: `decodeDataLoop` is `partial`, so it has no equational
lemmas).  Two independent decoders — PCB's Lean one and the generator's Python
one — agreeing on every payload is what turns the literals from an assumption
into a checked fact.  If the generator ever drifts, this module stops building.
-/
import WSC.Goldens.Decode
import WSC.Goldens.Terms

namespace WSC.Goldens.TermsCheck

open PlutusCore.Data (Data)

/-! ## Per-golden literal-vs-PCB-decoder equalities -/

/-- `programmableLogicBase.base-spend-no-global-or-seize-invoked-REJECT`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT :
    dataOfHex programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.scriptContextHex = some Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_ctx ∧
    dataOfHex programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.redeemerHex = some Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_redeemer ∧
    programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.paramsHex.filterMap dataOfHex = Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_params ∧
    programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.paramsHex.length = Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_params.length := by
  native_decide

/-- `programmableLogicBase.base-spend-transfer-tx`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableLogicBase_base_spend_transfer_tx :
    dataOfHex programmableLogicBase_base_spend_transfer_tx.scriptContextHex = some Terms.programmableLogicBase_base_spend_transfer_tx_ctx ∧
    dataOfHex programmableLogicBase_base_spend_transfer_tx.redeemerHex = some Terms.programmableLogicBase_base_spend_transfer_tx_redeemer ∧
    programmableLogicBase_base_spend_transfer_tx.paramsHex.filterMap dataOfHex = Terms.programmableLogicBase_base_spend_transfer_tx_params ∧
    programmableLogicBase_base_spend_transfer_tx.paramsHex.length = Terms.programmableLogicBase_base_spend_transfer_tx_params.length := by
  native_decide

/-- `programmableLogicGlobal.transfer-containment-violation-REJECT`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableLogicGlobal_transfer_containment_violation_REJECT :
    dataOfHex programmableLogicGlobal_transfer_containment_violation_REJECT.scriptContextHex = some Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_ctx ∧
    dataOfHex programmableLogicGlobal_transfer_containment_violation_REJECT.redeemerHex = some Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_redeemer ∧
    programmableLogicGlobal_transfer_containment_violation_REJECT.paramsHex.filterMap dataOfHex = Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_params ∧
    programmableLogicGlobal_transfer_containment_violation_REJECT.paramsHex.length = Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_params.length := by
  native_decide

/-- `programmableLogicGlobal.transfer-member-single-policy`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableLogicGlobal_transfer_member_single_policy :
    dataOfHex programmableLogicGlobal_transfer_member_single_policy.scriptContextHex = some Terms.programmableLogicGlobal_transfer_member_single_policy_ctx ∧
    dataOfHex programmableLogicGlobal_transfer_member_single_policy.redeemerHex = some Terms.programmableLogicGlobal_transfer_member_single_policy_redeemer ∧
    programmableLogicGlobal_transfer_member_single_policy.paramsHex.filterMap dataOfHex = Terms.programmableLogicGlobal_transfer_member_single_policy_params ∧
    programmableLogicGlobal_transfer_member_single_policy.paramsHex.length = Terms.programmableLogicGlobal_transfer_member_single_policy_params.length := by
  native_decide

/-- `programmableLogicGlobal.transfer-mixed-many-policies`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableLogicGlobal_transfer_mixed_many_policies :
    dataOfHex programmableLogicGlobal_transfer_mixed_many_policies.scriptContextHex = some Terms.programmableLogicGlobal_transfer_mixed_many_policies_ctx ∧
    dataOfHex programmableLogicGlobal_transfer_mixed_many_policies.redeemerHex = some Terms.programmableLogicGlobal_transfer_mixed_many_policies_redeemer ∧
    programmableLogicGlobal_transfer_mixed_many_policies.paramsHex.filterMap dataOfHex = Terms.programmableLogicGlobal_transfer_mixed_many_policies_params ∧
    programmableLogicGlobal_transfer_mixed_many_policies.paramsHex.length = Terms.programmableLogicGlobal_transfer_mixed_many_policies_params.length := by
  native_decide

/-- `programmableLogicGlobal.transfer-nonmember-covering-node`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableLogicGlobal_transfer_nonmember_covering_node :
    dataOfHex programmableLogicGlobal_transfer_nonmember_covering_node.scriptContextHex = some Terms.programmableLogicGlobal_transfer_nonmember_covering_node_ctx ∧
    dataOfHex programmableLogicGlobal_transfer_nonmember_covering_node.redeemerHex = some Terms.programmableLogicGlobal_transfer_nonmember_covering_node_redeemer ∧
    programmableLogicGlobal_transfer_nonmember_covering_node.paramsHex.filterMap dataOfHex = Terms.programmableLogicGlobal_transfer_nonmember_covering_node_params ∧
    programmableLogicGlobal_transfer_nonmember_covering_node.paramsHex.length = Terms.programmableLogicGlobal_transfer_nonmember_covering_node_params.length := by
  native_decide

/-- `programmableSeize.seize-1-input-missing-residual-output-REJECT`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableSeize_seize_1_input_missing_residual_output_REJECT :
    dataOfHex programmableSeize_seize_1_input_missing_residual_output_REJECT.scriptContextHex = some Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_ctx ∧
    dataOfHex programmableSeize_seize_1_input_missing_residual_output_REJECT.redeemerHex = some Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_redeemer ∧
    programmableSeize_seize_1_input_missing_residual_output_REJECT.paramsHex.filterMap dataOfHex = Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_params ∧
    programmableSeize_seize_1_input_missing_residual_output_REJECT.paramsHex.length = Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_params.length := by
  native_decide

/-- `programmableSeize.seize-1-input`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableSeize_seize_1_input :
    dataOfHex programmableSeize_seize_1_input.scriptContextHex = some Terms.programmableSeize_seize_1_input_ctx ∧
    dataOfHex programmableSeize_seize_1_input.redeemerHex = some Terms.programmableSeize_seize_1_input_redeemer ∧
    programmableSeize_seize_1_input.paramsHex.filterMap dataOfHex = Terms.programmableSeize_seize_1_input_params ∧
    programmableSeize_seize_1_input.paramsHex.length = Terms.programmableSeize_seize_1_input_params.length := by
  native_decide

/-- `programmableSeize.seize-2-inputs-partial-with-noise`: context, redeemer and 1 script parameter(s). -/
theorem lit_programmableSeize_seize_2_inputs_partial_with_noise :
    dataOfHex programmableSeize_seize_2_inputs_partial_with_noise.scriptContextHex = some Terms.programmableSeize_seize_2_inputs_partial_with_noise_ctx ∧
    dataOfHex programmableSeize_seize_2_inputs_partial_with_noise.redeemerHex = some Terms.programmableSeize_seize_2_inputs_partial_with_noise_redeemer ∧
    programmableSeize_seize_2_inputs_partial_with_noise.paramsHex.filterMap dataOfHex = Terms.programmableSeize_seize_2_inputs_partial_with_noise_params ∧
    programmableSeize_seize_2_inputs_partial_with_noise.paramsHex.length = Terms.programmableSeize_seize_2_inputs_partial_with_noise_params.length := by
  native_decide

/-- `programmableTokenMinting.mint-burnonly`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableTokenMinting_mint_burnonly :
    dataOfHex programmableTokenMinting_mint_burnonly.scriptContextHex = some Terms.programmableTokenMinting_mint_burnonly_ctx ∧
    dataOfHex programmableTokenMinting_mint_burnonly.redeemerHex = some Terms.programmableTokenMinting_mint_burnonly_redeemer ∧
    programmableTokenMinting_mint_burnonly.paramsHex.filterMap dataOfHex = Terms.programmableTokenMinting_mint_burnonly_params ∧
    programmableTokenMinting_mint_burnonly.paramsHex.length = Terms.programmableTokenMinting_mint_burnonly_params.length := by
  native_decide

/-- `programmableTokenMinting.mint-delegate-transfer-topup`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableTokenMinting_mint_delegate_transfer_topup :
    dataOfHex programmableTokenMinting_mint_delegate_transfer_topup.scriptContextHex = some Terms.programmableTokenMinting_mint_delegate_transfer_topup_ctx ∧
    dataOfHex programmableTokenMinting_mint_delegate_transfer_topup.redeemerHex = some Terms.programmableTokenMinting_mint_delegate_transfer_topup_redeemer ∧
    programmableTokenMinting_mint_delegate_transfer_topup.paramsHex.filterMap dataOfHex = Terms.programmableTokenMinting_mint_delegate_transfer_topup_params ∧
    programmableTokenMinting_mint_delegate_transfer_topup.paramsHex.length = Terms.programmableTokenMinting_mint_delegate_transfer_topup_params.length := by
  native_decide

/-- `programmableTokenMinting.mint-local-empty-withdrawals-REJECT`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableTokenMinting_mint_local_empty_withdrawals_REJECT :
    dataOfHex programmableTokenMinting_mint_local_empty_withdrawals_REJECT.scriptContextHex = some Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_ctx ∧
    dataOfHex programmableTokenMinting_mint_local_empty_withdrawals_REJECT.redeemerHex = some Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_redeemer ∧
    programmableTokenMinting_mint_local_empty_withdrawals_REJECT.paramsHex.filterMap dataOfHex = Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_params ∧
    programmableTokenMinting_mint_local_empty_withdrawals_REJECT.paramsHex.length = Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_params.length := by
  native_decide

/-- `programmableTokenMinting.mint-local-registered-by-ref`: context, redeemer and 2 script parameter(s). -/
theorem lit_programmableTokenMinting_mint_local_registered_by_ref :
    dataOfHex programmableTokenMinting_mint_local_registered_by_ref.scriptContextHex = some Terms.programmableTokenMinting_mint_local_registered_by_ref_ctx ∧
    dataOfHex programmableTokenMinting_mint_local_registered_by_ref.redeemerHex = some Terms.programmableTokenMinting_mint_local_registered_by_ref_redeemer ∧
    programmableTokenMinting_mint_local_registered_by_ref.paramsHex.filterMap dataOfHex = Terms.programmableTokenMinting_mint_local_registered_by_ref_params ∧
    programmableTokenMinting_mint_local_registered_by_ref.paramsHex.length = Terms.programmableTokenMinting_mint_local_registered_by_ref_params.length := by
  native_decide

/-! ## Aggregate

Every golden's three payload groups decode to the generated literals. -/
def allLiteralsAgree : Bool :=
  (dataOfHex programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.scriptContextHex == some Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_ctx &&
   dataOfHex programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.redeemerHex == some Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_redeemer &&
   programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.paramsHex.filterMap dataOfHex == Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_params &&
   programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT.paramsHex.length == Terms.programmableLogicBase_base_spend_no_global_or_seize_invoked_REJECT_params.length) &&
  (dataOfHex programmableLogicBase_base_spend_transfer_tx.scriptContextHex == some Terms.programmableLogicBase_base_spend_transfer_tx_ctx &&
   dataOfHex programmableLogicBase_base_spend_transfer_tx.redeemerHex == some Terms.programmableLogicBase_base_spend_transfer_tx_redeemer &&
   programmableLogicBase_base_spend_transfer_tx.paramsHex.filterMap dataOfHex == Terms.programmableLogicBase_base_spend_transfer_tx_params &&
   programmableLogicBase_base_spend_transfer_tx.paramsHex.length == Terms.programmableLogicBase_base_spend_transfer_tx_params.length) &&
  (dataOfHex programmableLogicGlobal_transfer_containment_violation_REJECT.scriptContextHex == some Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_ctx &&
   dataOfHex programmableLogicGlobal_transfer_containment_violation_REJECT.redeemerHex == some Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_redeemer &&
   programmableLogicGlobal_transfer_containment_violation_REJECT.paramsHex.filterMap dataOfHex == Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_params &&
   programmableLogicGlobal_transfer_containment_violation_REJECT.paramsHex.length == Terms.programmableLogicGlobal_transfer_containment_violation_REJECT_params.length) &&
  (dataOfHex programmableLogicGlobal_transfer_member_single_policy.scriptContextHex == some Terms.programmableLogicGlobal_transfer_member_single_policy_ctx &&
   dataOfHex programmableLogicGlobal_transfer_member_single_policy.redeemerHex == some Terms.programmableLogicGlobal_transfer_member_single_policy_redeemer &&
   programmableLogicGlobal_transfer_member_single_policy.paramsHex.filterMap dataOfHex == Terms.programmableLogicGlobal_transfer_member_single_policy_params &&
   programmableLogicGlobal_transfer_member_single_policy.paramsHex.length == Terms.programmableLogicGlobal_transfer_member_single_policy_params.length) &&
  (dataOfHex programmableLogicGlobal_transfer_mixed_many_policies.scriptContextHex == some Terms.programmableLogicGlobal_transfer_mixed_many_policies_ctx &&
   dataOfHex programmableLogicGlobal_transfer_mixed_many_policies.redeemerHex == some Terms.programmableLogicGlobal_transfer_mixed_many_policies_redeemer &&
   programmableLogicGlobal_transfer_mixed_many_policies.paramsHex.filterMap dataOfHex == Terms.programmableLogicGlobal_transfer_mixed_many_policies_params &&
   programmableLogicGlobal_transfer_mixed_many_policies.paramsHex.length == Terms.programmableLogicGlobal_transfer_mixed_many_policies_params.length) &&
  (dataOfHex programmableLogicGlobal_transfer_nonmember_covering_node.scriptContextHex == some Terms.programmableLogicGlobal_transfer_nonmember_covering_node_ctx &&
   dataOfHex programmableLogicGlobal_transfer_nonmember_covering_node.redeemerHex == some Terms.programmableLogicGlobal_transfer_nonmember_covering_node_redeemer &&
   programmableLogicGlobal_transfer_nonmember_covering_node.paramsHex.filterMap dataOfHex == Terms.programmableLogicGlobal_transfer_nonmember_covering_node_params &&
   programmableLogicGlobal_transfer_nonmember_covering_node.paramsHex.length == Terms.programmableLogicGlobal_transfer_nonmember_covering_node_params.length) &&
  (dataOfHex programmableSeize_seize_1_input_missing_residual_output_REJECT.scriptContextHex == some Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_ctx &&
   dataOfHex programmableSeize_seize_1_input_missing_residual_output_REJECT.redeemerHex == some Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_redeemer &&
   programmableSeize_seize_1_input_missing_residual_output_REJECT.paramsHex.filterMap dataOfHex == Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_params &&
   programmableSeize_seize_1_input_missing_residual_output_REJECT.paramsHex.length == Terms.programmableSeize_seize_1_input_missing_residual_output_REJECT_params.length) &&
  (dataOfHex programmableSeize_seize_1_input.scriptContextHex == some Terms.programmableSeize_seize_1_input_ctx &&
   dataOfHex programmableSeize_seize_1_input.redeemerHex == some Terms.programmableSeize_seize_1_input_redeemer &&
   programmableSeize_seize_1_input.paramsHex.filterMap dataOfHex == Terms.programmableSeize_seize_1_input_params &&
   programmableSeize_seize_1_input.paramsHex.length == Terms.programmableSeize_seize_1_input_params.length) &&
  (dataOfHex programmableSeize_seize_2_inputs_partial_with_noise.scriptContextHex == some Terms.programmableSeize_seize_2_inputs_partial_with_noise_ctx &&
   dataOfHex programmableSeize_seize_2_inputs_partial_with_noise.redeemerHex == some Terms.programmableSeize_seize_2_inputs_partial_with_noise_redeemer &&
   programmableSeize_seize_2_inputs_partial_with_noise.paramsHex.filterMap dataOfHex == Terms.programmableSeize_seize_2_inputs_partial_with_noise_params &&
   programmableSeize_seize_2_inputs_partial_with_noise.paramsHex.length == Terms.programmableSeize_seize_2_inputs_partial_with_noise_params.length) &&
  (dataOfHex programmableTokenMinting_mint_burnonly.scriptContextHex == some Terms.programmableTokenMinting_mint_burnonly_ctx &&
   dataOfHex programmableTokenMinting_mint_burnonly.redeemerHex == some Terms.programmableTokenMinting_mint_burnonly_redeemer &&
   programmableTokenMinting_mint_burnonly.paramsHex.filterMap dataOfHex == Terms.programmableTokenMinting_mint_burnonly_params &&
   programmableTokenMinting_mint_burnonly.paramsHex.length == Terms.programmableTokenMinting_mint_burnonly_params.length) &&
  (dataOfHex programmableTokenMinting_mint_delegate_transfer_topup.scriptContextHex == some Terms.programmableTokenMinting_mint_delegate_transfer_topup_ctx &&
   dataOfHex programmableTokenMinting_mint_delegate_transfer_topup.redeemerHex == some Terms.programmableTokenMinting_mint_delegate_transfer_topup_redeemer &&
   programmableTokenMinting_mint_delegate_transfer_topup.paramsHex.filterMap dataOfHex == Terms.programmableTokenMinting_mint_delegate_transfer_topup_params &&
   programmableTokenMinting_mint_delegate_transfer_topup.paramsHex.length == Terms.programmableTokenMinting_mint_delegate_transfer_topup_params.length) &&
  (dataOfHex programmableTokenMinting_mint_local_empty_withdrawals_REJECT.scriptContextHex == some Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_ctx &&
   dataOfHex programmableTokenMinting_mint_local_empty_withdrawals_REJECT.redeemerHex == some Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_redeemer &&
   programmableTokenMinting_mint_local_empty_withdrawals_REJECT.paramsHex.filterMap dataOfHex == Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_params &&
   programmableTokenMinting_mint_local_empty_withdrawals_REJECT.paramsHex.length == Terms.programmableTokenMinting_mint_local_empty_withdrawals_REJECT_params.length) &&
  (dataOfHex programmableTokenMinting_mint_local_registered_by_ref.scriptContextHex == some Terms.programmableTokenMinting_mint_local_registered_by_ref_ctx &&
   dataOfHex programmableTokenMinting_mint_local_registered_by_ref.redeemerHex == some Terms.programmableTokenMinting_mint_local_registered_by_ref_redeemer &&
   programmableTokenMinting_mint_local_registered_by_ref.paramsHex.filterMap dataOfHex == Terms.programmableTokenMinting_mint_local_registered_by_ref_params &&
   programmableTokenMinting_mint_local_registered_by_ref.paramsHex.length == Terms.programmableTokenMinting_mint_local_registered_by_ref_params.length)

theorem allLiteralsAgree_true : allLiteralsAgree = true := by native_decide

end WSC.Goldens.TermsCheck
